version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker container
          command: docker build -t ci-test-docker-microservice-template ./ --no-cache
      - save_cache:
          key: docker_cache_ci
          paths:
            - docker-cache
  publish-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - restore_cache:
          key: docker_cache_ci
      - setup_remote_docker
      - run:
          name: Load Image from Cache
          command: docker load < docker-cache/ci-test-docker-microservice-template.tar
      - run:
          name: Tag the docker image
          command: docker tag ci-test-docker-microservice-template:latest 367608115228.dkr.ecr.eu-central-1.amazonaws.com/ci-test-docker-microservice-template:latest
      - run:
          name: Push the docker image
          command: docker push 367608115228.dkr.ecr.eu-central-1.amazonaws.com/ci-test-docker-microservice-template:latest
workflows:
  version: 2
  build-publish-image:
    jobs:
      - build
      - publish-image:
          requires:
            - build
          filters:
            branches:
              only: master
