version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          name: Build docker container
          command: docker build -t docker-microservice-template ./ --no-cache
